# Generated by Django 4.0 on 2023-03-07 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_order_date_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitchens',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 10, 37, 7, 848904, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 10, 37, 7, 849065, tzinfo=utc)),
        ),
    ]
